import Chat from '../models/Chat.js'; import User from '../models/User.js'; import fs from 'fs/promises'; import {solveDoubt,detectedSubject} from '../services/geminiService.js';import {transcribe} from '../services/speechService.js';
const owned=async(id,user)=>Chat.findOne({_id:id,user}); const url=f=>`/uploads/${f.mimetype.startsWith('image/')?'images':'audio'}/${f.filename}`;
export const list=async(req,res)=>res.json(await Chat.find({user:req.user._id,isArchived:false}).select('title subject lastActivity messages').sort({lastActivity:-1}));
export const create=async(req,res)=>res.status(201).json(await Chat.create({user:req.user._id,title:req.body.title||'New doubt'}));
export const get=async(req,res)=>{const c=await owned(req.params.id,req.user._id);if(!c)return res.status(404).json({message:'Chat not found.'});res.json(c)};
export const remove=async(req,res)=>{const c=await owned(req.params.id,req.user._id);if(!c)return res.status(404).json({message:'Chat not found.'});await c.deleteOne();res.status(204).end()};
export const stats=async(req,res)=>{const chats=await Chat.find({user:req.user._id});const subjects={};chats.forEach(c=>{subjects[c.subject]=(subjects[c.subject]||0)+c.messages.filter(m=>m.role==='user').length});res.json({totalChats:chats.length,totalDoubts:req.user.totalDoubts,subjects})};
async function submit(req,res,type){const chat=await owned(req.params.id,req.user._id);if(!chat)return res.status(404).json({message:'Chat not found.'});let question=req.body.text?.trim(),file=req.file,mediaUrl,fileContent,transcriptText;try{if(type==='text'&&!question)return res.status(400).json({message:'Please enter a question.'});if(type!=='text'&&!file)return res.status(400).json({message:`Please attach a ${type} file.`});if(file){mediaUrl=url(file);if(type==='image')fileContent=(await fs.readFile(file.path)).toString('base64');if(type==='voice'){transcriptText=await transcribe(file.path);question=transcriptText}}const userMessage={role:'user',content:question||'Image question',inputType:type,...(type==='image'?{imageUrl:mediaUrl}:type==='voice'?{audioUrl:mediaUrl}:{})};chat.messages.push(userMessage);const answer=await solveDoubt({text:question,imageBase64:fileContent,mimeType:file?.mimetype,transcript:transcriptText,history:chat.messages.slice(0,-1)});chat.messages.push({role:'assistant',content:answer,inputType:'text'});chat.subject=chat.subject==='General'?detectedSubject(answer):chat.subject;chat.title=chat.messages.filter(m=>m.role==='user').length===1?(question||'Image doubt').slice(0,65):chat.title;chat.lastActivity=new Date();await chat.save();await User.findByIdAndUpdate(req.user._id,{$inc:{totalDoubts:1}});res.json({chat,transcript:transcriptText})}catch(error){if(file)await fs.unlink(file.path).catch(()=>{});throw error}}
export const text=(req,res)=>submit(req,res,'text');export const image=(req,res)=>submit(req,res,'image');export const voice=(req,res)=>submit(req,res,'voice');
